//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeReviewApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeRating
    {
        public int EmployeeRatingsID { get; set; }
        public int EmployeeID { get; set; }
        public Nullable<int> SkillsID { get; set; }
        public Nullable<int> RatingsID { get; set; }
        public string Comments { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Rating Rating { get; set; }
        public virtual Skill Skill { get; set; }
    }
}
