//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeReviewApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SkillType
    {
        public int SkillTypeID { get; set; }
        public string SkillTypeName { get; set; }
    }
}
